POST http://localhost:3002/exercises HTTP/1.1
content-type: application/json

{
  "daily_exercises": [1, 0, 2, 0, 3, 0, "2.5"],
  "target": 2.5
}

### Normal
POST http://localhost:3002/api/patients HTTP/1.1
content-type: application/json

{
    "name": "aaa",
    "dateOfBirth": "1992-5-5",
    "ssn": "123456",
    "gender": "female",
    "occupation": "NPC"
}

### protection
POST http://localhost:3002/api/patients HTTP/1.1
content-type: application/json

{
    "name": "aaa",
    "dateOfBirth": "1992-5-5",
    "ssn": 123333,
    "gender": "female",
    "occupation": "NPC"
}

### post to entry
POST http://localhost:3002/api/patients/d2773822-f723-11e9-8f0b-362b9e155667/entries
content-type: application/json

{
  "date": "2020-01-02",
  "type": "Hospital",
  "specialist": "sdfdsfewf",
  "diagnosisCodes": ["S62.5"],
  "description":
    "Healing time appr. 2 weeks. patient doesn't remember how he got the injury.",
  "discharge": {
    "date": "2021-01-02",
    "criteria": "Thumb has healed."
  }
}
